version: '3.4'

services:
  phase3section4:
    image: ${DOCKER_REGISTRY-}phase3section4
    build:
      context: .
      dockerfile: Phase3Section4/Dockerfile
    ports:
      - "44494:44494"
    depends_on:
      - phase3section4a

  phase3section4a:
    image: ${DOCKER_REGISTRY-}phase3section4a
    build:
      context: .
      dockerfile: Phase3Section4a/Dockerfile
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "!QWe4567"
        ACCEPT_EULA: "Y"